/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CalculadoraDieta;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        Scanner scan = new Scanner(System.in);
        
        pessoa objetoPessoa = new pessoa();
        
        System.out.println("Digite o peso: ");
        objetoPessoa.setPeso(scan.nextFloat());
        
        System.out.println("Digite a altura em centímetros: ");
        objetoPessoa.setAltura(scan.nextFloat());
        
        System.out.println("Digite a idade");
        objetoPessoa.setIdade(scan.nextInt());
        
        System.out.println("A taxa de metabolismo basal é " + objetoPessoa.calcularTmb());
    }
}
