/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
      Scanner scan = new Scanner(System.in);
      
       pessoa objetoPessoa = new pessoa();
       
        System.out.println("Digite o peso: ");
        objetoPessoa.peso = scan.nextFloat();
        
        System.out.println("Digite a altura: ");
        objetoPessoa.altura = scan.nextFloat();
        
        System.out.println("IMC = " + objetoPessoa.calcularIMC());
    }
}
