/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
      Scanner scan = new Scanner(System.in);
      
       pessoa objetoPessoa = new pessoa();
       
        System.out.println("Digite o peso: ");
        objetoPessoa.setPeso(scan.nextFloat()); // o que for digitado vai alterar o objeto e não a entidade
        // o objeto gerencia a suas informações
        
        System.out.println("Digite a altura: ");
        objetoPessoa.setAltura(scan.nextFloat());
        
        // os metodos devem ser nomeados no infinitivo como "calcular". Com exeção do método construtor
        
        System.out.println("IMC = " + objetoPessoa.calcularIMC());
    }
}
/*Já aqui na main fica tudo referente a interação do app com o usuário*/
