/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class Principal {
    
    public static void main(String[] args) {
        System.out.println("Ola mundo!");
    }

}

    

