/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicioPOO1;

import java.util.Scanner;

public class App {
       public static void main(String[] args) {
       Scanner scan = new Scanner(System.in);
           pessoa objetoPessoa = new pessoa();
           
           System.out.println("Informe o nome: ");
           objetoPessoa.setNome(scan.next());
           
           System.out.println("Informe a data de nascimento yyy-mm-dd ");
           objetoPessoa.setDataNascimento(scan.nextLine());
    
           System.out.println("Nome: " + objetoPessoa.getNome() + "Data: " + objetoPessoa.calcularData());
    }
}

// não consegui fazer o calculo de ano
/*1. Crie uma classe para representar uma Pessoa com os atributos privados de nome, data de nascimento e 
altura. Crie os métodos públicos necessários para getters e setters e também um método para imprimir 
todos dados de uma pessoa. Crie um método para calcular a idade da pessoa.*/